# Site settings
title: "Juan Olivera Resume"
description: "Juan Olivera Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Juan Olivera"
resume_title:                   "Software Architect"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "juam17@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+54) 911 6366 8353"
resume_contact_address:         "Buenos Aires, Argentina"

resume_header_contact_info:     "Buenos Aires, Argentina • (+54) 911 6366 8353 • juam17@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hands-on Software Architect with 15+ years of experience building and leading software products.</p><p>Passionate about resolving problem and technical challenges. Strong team member, fast learner and self-motivated.</p><p>Specialties: Software Architecture, Design and Development of Web Applications, Microservices, BigData, DevOps, Cloud Computing, and Agile Software Development.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true
resume_section_technology:     true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jpOlivo"
  resume_twitter_url:           "http://twitter.com/jp_olivo"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/juan-pablo-olivera-275790b/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://jpolivo.github.io/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts